import { useEffect, useState } from 'react';
import { AnimatePresence, motion, MotionConfig } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, Bookmark, Check, ChevronDown, CircleHelp, Compass, Fingerprint, Globe2, Grid2X2, HeartHandshake, Layers3, LayoutList, LockKeyhole, Menu, Search, ShieldCheck, Sparkles, Sprout, Wallet, X } from 'lucide-react';
import { Artwork } from './components/Artwork';
import { BidWorkspace } from './components/BidWorkspace';
import { Modal } from './components/Modal';
import { WalletModal } from './components/WalletModal';
import { rooms, money, deadlineLabel, type Room } from './data/rooms';
import { WalletController, friendlyError, type WalletChoice, type WalletSession, type Network } from './lib/wallet';
import { getMetrics } from './lib/api';
import { readDeployment, type Deployment } from './lib/receipts';
import { vaultKey } from './lib/vault';

const controller = new WalletController();
type Page = 'explore' | 'studio' | 'saved' | 'community';
function readSaved(): string[] { try { const value = JSON.parse(localStorage.getItem('roda:saved') || '[]'); return Array.isArray(value) ? value.filter(id => typeof id === 'string') : []; } catch { return []; } }

export default function App() {
  const [page, setPage] = useState<Page>('explore');
  const [mobileMenu, setMobileMenu] = useState(false);
  const [saved, setSaved] = useState<string[]>(readSaved);
  const [category, setCategory] = useState('All disciplines');
  const [query, setQuery] = useState('');
  const [list, setList] = useState(false);
  const [activeRoom, setActiveRoom] = useState<Room | null>(null);
  const [walletOpen, setWalletOpen] = useState(false);
  const [privacyOpen, setPrivacyOpen] = useState(false);
  const [session, setSession] = useState<WalletSession | null>(null);
  const [network, setNetwork] = useState<Network>('preview');
  const [walletError, setWalletError] = useState('');
  const [storageNotice, setStorageNotice] = useState('');
  const [metrics, setMetrics] = useState<{ verified_transactions: number; reported_receipts: number } | null>(null);
  const [revision, setRevision] = useState(0);
  useEffect(() => { let live = true; void getMetrics().then(result => { if (live) setMetrics(result); }); return () => { live = false; }; }, []);
  useEffect(() => {
    if (!session) return;
    const timer = setInterval(() => {
      void session.api.getConnectionStatus().then(status => {
        if (status.status !== 'connected' || status.networkId !== network) { controller.disconnect(); setSession(null); }
      }).catch(() => { controller.disconnect(); setSession(null); });
    }, 15000);
    return () => clearInterval(timer);
  }, [session, network]);
  const navigate = (next: Page) => { setPage(next); setMobileMenu(false); setQuery(''); setCategory('All disciplines'); };
  function toggleSaved(id: string) {
    const next = saved.includes(id) ? saved.filter(value => value !== id) : [...saved, id];
    try { localStorage.setItem('roda:saved', JSON.stringify(next)); setSaved(next); } catch { setStorageNotice('This browser could not save your shortlist. Check available storage.'); }
  }
  async function connect(choice: WalletChoice) {
    setWalletError('');
    try { setSession(await controller.connect(choice)); setWalletOpen(false); }
    catch (err) { setWalletError(friendlyError(err)); }
  }
  const filtered = rooms.filter(room => (page !== 'saved' || saved.includes(room.id))
    && (category === 'All disciplines' || room.category === category)
    && `${room.title} ${room.organization} ${room.tags.join(' ')} ${room.location}`.toLowerCase().includes(query.toLowerCase()));
  const deployments = session ? rooms.map(room => ({ room, deployment: readDeployment(vaultKey(network, session.fingerprint, room.id)) }))
    .filter((entry): entry is { room: Room; deployment: Deployment } => Boolean(entry.deployment)) : [];
  void revision;
  return <MotionConfig reducedMotion="user"><div className="app-shell">
    <a className="skip-link" href="#main">Skip to content</a>
    {mobileMenu && <button className="mobile-scrim" aria-label="Close navigation" onClick={() => setMobileMenu(false)}/>}
    <aside className={`sidebar ${mobileMenu ? 'is-open' : ''}`}>
      <button className="wordmark" onClick={() => navigate('explore')} aria-label="RODA home"><img src="/mark.svg" alt=""/><span>roda<span className="wordmark-dot">®</span></span></button>
      <div className="sidebar-kicker">INDEPENDENT MINDS.<br/>COLLECTIVE FUTURES.</div>
      <span className="nav-label">YOUR COMMON GROUND</span>
      <nav aria-label="Main navigation">
        {([{ id: 'explore', label: 'Explore', icon: Compass }, { id: 'studio', label: 'My workspace', icon: Layers3 }, { id: 'saved', label: 'Saved commissions', icon: Bookmark }, { id: 'community', label: 'The community', icon: HeartHandshake }] as const).map(item => <button key={item.id} onClick={() => navigate(item.id)} className={`nav-item ${page === item.id ? 'active' : ''}`} aria-current={page === item.id ? 'page' : undefined}><item.icon size={19}/><span>{item.label}</span>{item.id === 'saved' && saved.length > 0 && <span className="nav-count">{saved.length}</span>}{page === item.id && <span className="nav-active-dot"/>}</button>)}
      </nav>
      <div className="sidebar-bottom"><div className="sidebar-note"><div className="note-spark">✳</div><span className="eyebrow">A FAIRER WAY FORWARD</span><h3>Less undercutting.<br/>More possibility.</h3><p>Your work deserves a fair shot. Your price deserves privacy.</p><button className="text-button" onClick={() => setPrivacyOpen(true)}>Meet sealed bidding <ArrowUpRight size={15}/></button></div>
        <button className="support-link" onClick={() => setPrivacyOpen(true)}><CircleHelp size={17}/> A little guidance <ArrowUpRight size={14}/></button><div className="sidebar-footer"><span className="midnight-symbol">◒</span> Powered by Midnight<span className="status-dot"/></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu-button" aria-label="Open navigation" onClick={() => setMobileMenu(true)}><Menu size={22}/></button><span className="breadcrumb-icon"><Compass size={18}/></span><span>{page === 'explore' ? 'Explore' : page === 'studio' ? 'My workspace' : page === 'saved' ? 'Saved commissions' : 'The community'}</span><span className="breadcrumb-slash">/</span><strong>Common ground</strong></div><div className="topbar-actions"><div className="network-control"><span className="status-dot"/><select aria-label="Midnight network" value={network} onChange={e => { const value = e.target.value as Network; controller.switchNetwork(value); setSession(null); setNetwork(value); setActiveRoom(null); }}><option value="preview">Preview</option><option value="preprod">Preprod</option></select><ChevronDown size={12}/></div><button className={`button wallet-button ${session ? 'connected' : 'dark'}`} onClick={() => setWalletOpen(true)}>{session ? <Check size={16}/> : <Wallet size={16}/>}<span>{session ? session.name : 'Connect 1AM'}</span></button></div></header>
    <main id="main" className="main-content">
      <AnimatePresence mode="wait"><motion.div key={page} initial={{ opacity: 0, y: 9 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: .22 }}>
      {page === 'explore' && <>
        <div className="page-heading"><div><div className="eyebrow greeting"><span className="tiny-star">✳</span> THERE’S GOOD WORK TO BE DONE.</div><h1>Good work.<br/>On <span className="serif">your</span> terms.</h1><p>A shared space for independent talent and collective ambition.<br className="desktop-break"/> Find your people. Name your price. Keep it yours.</p></div><div className="heading-note"><div className="community-orbits"><span/><span/><span/><span/></div><strong>Built around people.<br/>Protected by proof.</strong><button className="text-button" onClick={() => setPrivacyOpen(true)}>How RODA works <ArrowUpRight size={15}/></button></div></div>
        <section className="feature-grid" aria-label="Featured commission"><article className="featured-card"><div className="featured-copy"><span className="eyebrow"><span className="status-dot"/> IN THE SPOTLIGHT <span className="sample-label">SAMPLE</span></span><div className="featured-title"><span>01 / SOLAR COMMONS</span><h2>Build something<br/>we can all<br/><span className="serif">belong to.</span></h2></div><p>A gathering space powered by the sun.<br/>Shaped by independent minds like yours.</p><div className="feature-bottom"><button className="button dark" onClick={() => setActiveRoom(rooms[0])}>Explore the commission <ArrowUpRight size={16}/></button><span>Salvador, BR</span></div></div><Artwork large/><div className="feature-sticker"><Sprout size={16}/> COMMUNITY-LED<br/>FUTURE-FOCUSED</div></article>
          <aside className="privacy-card"><div className="privacy-top"><span className="eyebrow">YOUR EDGE IS YOURS.</span><LockKeyhole size={19}/></div><h2>Talent, visible.<br/>Offers, <span className="serif">private.</span></h2><p>No racing to the bottom.<br/>No showing your hand.<br/>Just a fairer starting line.</p><div className="privacy-orbit"><div/><div/><div/><span><Fingerprint size={30}/></span></div><button onClick={() => setPrivacyOpen(true)}>A little privacy. A lot of possibility. <ArrowUpRight size={17}/></button></aside>
        </section>
        <div className="community-strip"><div className="strip-mark"><HeartHandshake size={20}/></div><strong>Good things happen in a roda.</strong><p>A circle. A meeting place. A chance to move forward, together.</p><button className="text-button" onClick={() => navigate('community')}>Meet the idea <ArrowRight size={16}/></button></div>
      </>}
      {(page === 'explore' || page === 'saved') && <section className="commission-section">
        <div className="section-heading"><div><span className="eyebrow">{page === 'saved' ? 'KEEP THE POSSIBILITIES CLOSE' : 'MAKE YOUR NEXT MOVE'}</span><h2>{page === 'saved' ? 'Your shortlist.' : 'Find your next commission.'}<span className="count-pill">{filtered.length.toString().padStart(2, '0')}</span></h2></div><div className="view-toggle" aria-label="Commission layout"><button className={!list ? 'selected' : ''} aria-label="Grid view" aria-pressed={!list} onClick={() => setList(false)}><Grid2X2 size={17}/></button><button className={list ? 'selected' : ''} aria-label="List view" aria-pressed={list} onClick={() => setList(true)}><LayoutList size={19}/></button></div></div>
        <div className="filter-bar"><div className="category-tabs" aria-label="Filter discipline">{['All disciplines', 'Design & build', 'Sound & culture', 'Objects & craft'].map(cat => <button key={cat} className={category === cat ? 'selected' : ''} onClick={() => setCategory(cat)} aria-pressed={category === cat}>{cat}</button>)}</div><label className="search"><Search size={16}/><input type="search" aria-label="Search commissions" placeholder="Find your thing…" value={query} onChange={e => setQuery(e.target.value)}/>{query && <button className="icon-button" aria-label="Clear search" onClick={() => setQuery('')}><X size={13}/></button>}</label></div>
        {filtered.length ? <div className={`commission-grid ${list ? 'list-layout' : ''}`}>{filtered.map((room, index) => <motion.article className="commission-card" key={room.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }}><div className="card-art"><Artwork variant={room.color}/><span className="card-category">{room.category}</span><button className={`save-button ${saved.includes(room.id) ? 'is-saved' : ''}`} aria-label={`${saved.includes(room.id) ? 'Unsave' : 'Save'} ${room.organization}`} aria-pressed={saved.includes(room.id)} onClick={() => toggleSaved(room.id)}><Bookmark size={17} fill={saved.includes(room.id) ? 'currentColor' : 'none'}/></button></div><div className="card-copy"><div className="organization"><span className={`org-avatar ${room.color}`}>{index === 0 ? <Sprout size={15}/> : index === 1 ? <Sparkles size={15}/> : <Layers3 size={15}/>}</span>{room.organization}<span className="sample-label">SAMPLE</span></div><h3><button onClick={() => setActiveRoom(room)}>{room.title}</button></h3><p>{room.summary}</p><div className="tags">{room.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="card-details"><div><span>PUBLIC PRICE BAND</span><strong>{money(room.minimum)}–{money(room.maximum)}</strong></div><span className="duration">{room.duration}</span></div><div className="card-footer"><span><LockKeyhole size={13}/> Sealed offers</span><span>Closes {deadlineLabel(room.deadline)}</span><button className="card-arrow" aria-label={`Open ${room.organization} commission`} onClick={() => setActiveRoom(room)}><ArrowUpRight size={18}/></button></div></div></motion.article>)}</div>
          : <div className="empty-state"><Bookmark size={32}/><h3>{page === 'saved' ? 'A little space for what’s next.' : 'Nothing in this corner just yet.'}</h3><p>{page === 'saved' ? 'Save a commission that speaks to you. Your shortlist stays on this device.' : 'Try another discipline or a different search.'}</p><button className="button dark" onClick={() => { navigate('explore'); setQuery(''); }}>Explore commissions <ArrowRight size={16}/></button></div>}
        <div className="catalog-note"><span className="status-dot muted-dot"/><p>A public sample catalog to explore the experience. Wallet actions use the real {network} network. No live participation or funding is implied.</p><span>03 POSSIBILITIES. YOUR NEXT CHAPTER.</span></div>
      </section>}
      {page === 'studio' && <><div className="page-heading"><div><span className="eyebrow">INDEPENDENCE, WITH A HOME</span><h1>Your work.<br/>Your <span className="serif">workspace.</span></h1><p>Your contracts and receipts, scoped to your connected wallet.<br/>Private offers stay encrypted on this device.</p></div><Fingerprint className="page-illustration" size={100}/></div><div className="workspace-stats"><div><span>YOUR WORKER CONTRACTS</span><strong>{deployments.length.toString().padStart(2, '0')}</strong></div><div><span>NETWORK</span><strong className="network-name">{network}</strong></div><div><span>LOCAL PRIVACY</span><strong><ShieldCheck size={28}/> On your terms</strong></div></div>{!session ? <div className="empty-state"><Wallet size={35}/><h3>Your workspace begins with you.</h3><p>Connect 1AM to find the worker contracts retained for your wallet.</p><button className="button dark" onClick={() => setWalletOpen(true)}>Connect 1AM <ArrowUpRight size={16}/></button></div> : !deployments.length ? <div className="empty-state"><Layers3 size={36}/><h3>Room for your first good thing.</h3><p>Open a commission to prepare an offer or unlock an existing draft.<br/>Deploy your own contract when you’re ready.</p><button className="button dark" onClick={() => navigate('explore')}>Find a commission <ArrowRight size={16}/></button></div> : <div className="deployment-list">{deployments.map(({ room, deployment }) => <button key={room.id} onClick={() => setActiveRoom(room)}><span className={`org-avatar ${room.color}`}><Fingerprint size={20}/></span><span><strong>{room.organization}</strong><small>{deployment.receipt.contractAddress}</small></span><span className="pill">{deployment.phase}</span><ArrowUpRight size={20}/></button>)}</div>}</>}
      {page === 'community' && <><div className="page-heading"><div><span className="eyebrow">THE FUTURE HAS ROOM FOR ALL OF US</span><h1>Come full <span className="serif">circle.</span></h1><p>RODA takes its name from a circle: a place to gather,<br/>exchange ideas, and build something larger than ourselves.</p></div><HeartHandshake size={85} strokeWidth={1} className="page-illustration"/></div><div className="community-manifesto"><Artwork large variant="lime"/><div><span className="eyebrow">A COMMUNITY, BY DESIGN</span><h2>Bring your skills.<br/>Keep your agency.</h2><p>Independent work should begin with possibility. Here, public briefs create a common starting point, while private offers give each person space to decide what their work is worth.</p><p>This preview explores that idea through sample creative commissions. It is an invitation to test a fairer process, with real privacy proofs and transparent limits.</p><button className="button dark" onClick={() => navigate('explore')}>Find your common ground <ArrowUpRight size={17}/></button></div></div><div className="principle-grid">{[{ n: '01', title: 'Respect the work.', text: 'Public price bands set expectations. No public leaderboard of private prices.' }, { n: '02', title: 'Leave room for choice.', text: 'A sealed offer stays hidden. Its owner chooses whether to open it after the deadline.' }, { n: '03', title: 'Build in the open.', text: 'Contract addresses, finalization, and disclosure rules are visible. Private inputs are not.' }].map(p => <article key={p.n}><span className="eyebrow">{p.n} / OUR COMMON GROUND</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div><div className="community-metrics"><strong>{metrics ? metrics.verified_transactions : '—'}</strong><span>Independently verified public transactions{!metrics && <small>Public API is not connected. No activity is invented.</small>}{metrics && <small>{metrics.reported_receipts} client-reported receipts · excluded from this count</small>}</span></div></>}
      </motion.div></AnimatePresence>
      {storageNotice && <p className="error" role="alert">{storageNotice}</p>}
      <footer className="main-footer"><span><img src="/mark.svg" alt=""/> A LITTLE INDEPENDENCE. A LOT OF TOGETHER.</span><button className="text-button" onClick={() => setPrivacyOpen(true)}>Privacy is part of the fabric <ShieldCheck size={14}/></button></footer>
    </main></div>
    {activeRoom && !walletOpen && <BidWorkspace key={`${activeRoom.id}:${session?.fingerprint || 'guest'}:${network}`} room={activeRoom} session={session} onClose={() => setActiveRoom(null)} onConnect={() => setWalletOpen(true)} onUpdate={() => setRevision(value => value + 1)}/>}
    {walletOpen && <WalletModal onClose={() => setWalletOpen(false)} onConnect={connect} session={session} error={walletError} disconnect={() => { controller.disconnect(); setSession(null); setWalletOpen(false); }}/ >}
    {privacyOpen && <Modal title="A fair shot. A private offer." onClose={() => setPrivacyOpen(false)}><p className="muted">A zero-knowledge proof lets the network check that your offer meets the public rules without seeing the amount.</p><div className="privacy-steps"><div><span>01</span><strong>Find your common ground</strong><p>Read the public commission, price band, and closing date.</p></div><ArrowDown size={18}/><div><span>02</span><strong>Make room for your offer</strong><p>Save your private price, salt, and worker secret in an encrypted vault on your device. Keep a backup and your passphrase.</p></div><ArrowDown size={18}/><div><span>03</span><strong>Connect. Deploy. Seal.</strong><p>Your 1AM wallet deploys your own worker contract and approves the proof transaction. The finalized address and deployment hash are retained.</p></div><ArrowDown size={18}/><div><span>04</span><strong>Open only when you choose</strong><p>After the deadline, you can irreversibly reveal your exact price. There is no automatic winner selection, escrow, or payment.</p></div></div><div className="notice"><Globe2 size={18}/><p>Public: commission rules, commitments, replay tags, contract addresses, transaction timing, and voluntary openings. A per-worker contract is linkable across its actions and does not prove unique human identity.</p></div><p className="fine-print">Your wallet’s prover is a separate trust boundary and may see private witnesses. RODA’s API and Gemini receive no private offer values. This preview is for network testing, not handling client funds.</p><button className="button dark full" onClick={() => setPrivacyOpen(false)}>Got it. Let’s find good work. <ArrowRight size={16}/></button></Modal>}
  </div></MotionConfig>;
}
